name: scheduled-api-call

on:
  schedule:
    - cron: '30 20 23 5 *'   # UTC 時間：5/23 晚上 21:00
  workflow_dispatch:        # 可手動觸發

jobs:
  call:
    if: github.event_name == 'schedule' && github.event.schedule == '30 20 23 5 *'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Call API
        run: node ./index.js
