name: scheduled-api-call            # 工作流程名稱（隨意）

on:
  schedule:
    - cron: '*/10 * * * *'          # 每 10 分鐘（最小 5 分鐘）:contentReference[oaicite:1]{index=1}
  workflow_dispatch:                # 允許手動觸發（方便測試）

jobs:
  call:
    runs-on: ubuntu-latest          # GitHub 代管 runner
    steps:
      - name: Check out repoinit
        uses: actions/checkout@v4

      - name: Call API
        run: node ./index.js
